version: '3.9'

services:
  postgres:
    image: postgres:alpine
    container_name: capstone-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: capstone

  node:
    image: node:alpine
    container_name: capstone-node
    restart: always
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "yarn && yarn dev"
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
